#' Add points, coordinates, or polygons to a list of spatial plots
#'
#' @param r_frame_list list of ggplots, as generated by \code{\link{ts_makeframes}}.
#' @param positions object containing the coordinates. One of \itemize{
##'  \item{A two-column \code{matrix} of coordinates where the first column corresponds to the longitude and the second column corresponds to the latitude.}
##'  \item{A \code{SpatialPolygonsDataFrame} from which \link[sp]{coordinates} can be extracted.}
##'  \item{A \code{SpatialPointsDataFrame} from which \link[sp]{coordinates} can be extracted.}
##' }
#' @param position_names (Optional) character, names of the positions to be added in legend or text (If \code{add_text}). By default, will create placeholder names by combining the object type and Id (Example: *"Polygon 3"*)
#' @param pcol (Optional) character, color of the spatial objects. Default is \code{"red"}.
#' @param psize  (Optional) numeric, plot size of the spatial objects. Default is \code{2}.
#' @param position_legend_title  (Optional) character, title of the legend. Default is \code{"Position"}.
#' @param legend_position  (Optional) character, position of the legend. Use \code{"none"} to disable the legend. Default is \code{"right"}
#' @param aes_by_pos (Optional) logical. If \code{TRUE}: vary some aesthetic (linetype for polygons, shape for points) to be different for each position? If  \code{FALSE}, this also disables the legend, as no notable classes will be plotted. Default is \code{FALSE}. 
#' @param tcol (Optional) character, if \code{add_text}: The color of the text. Default is \code{"red"}.
#' @param tsize (Optional) numeric, if \code{add_text}: The size of the text. Default is \code{7}.
#' @param ttype (Optional) character, if \code{add_text}: The type of the text. Either \code{"label"} or \code{"text"}. Default is \code{"text"}.
#' @param t_hjust (Optional) numeric, if \code{add_text}: Horizontal offset of the text in map units. Default is \code{0}.
#' @param t_vjust (Optional) numeric, if \code{add_text}: Vertical offset of the text in map units. Default is \code{0}.
#' @param add_text (Optional) logical.  If \code{TRUE}: add a text to each position using \link[moveVis]{add_text}.  Default is \code{"False"}.
#'
#' @details The function takes a \code{positions} object, which can be a spatial object or a matrix of coordinates, and adds them to each of the elements of \code{r_frame_list} using \link[moveVis]{add_gg}. Optionally it also adds text at their respective positions using\link[moveVis]{add_text}.
#' 
#' - \code{ts_add_positions_to_frames} is intended to be an easy way to add multiple objects to the spatial frames at fixed positions. 
#' For adding individual positions or text, potentially at varying positions, it is recommended to all \link[moveVis]{add_gg} and \link[moveVis]{add_text} directly.
#' @seealso \link[moveVis]{add_text} \link[moveVis]{add_gg}
#' @importFrom moveVis add_text add_gg
#' @importFrom sp coordinates
#' @author Johannes Mast
#' @return A list of ggplots with added positions.
#' @export
ts_add_positions_to_frames <- function(r_frame_list,positions,position_names=NULL,pcol="red",tcol="red",psize=2,tsize=7,ttype="text",t_hjust=0,t_vjust=0,position_legend_title = "Position",legend_position="right",aes_by_pos=F,add_text=F){
  
  
  
  if(inherits(positions,"SpatialPolygonsDataFrame")){
    data <-  fortify(positions);data$id <- as.factor(data$id)
    if(is.null(position_names)){
      position_names <- paste("Polygon" ,(1:nrow(positions)))
    }else{
       position_names <- as.factor(position_names)
    }
    levels(data$id) <- position_names
    
    if(aes_by_pos){
      outlist <- moveVis::add_gg(r_frame_list, gg = expr(
        list(
          geom_path(aes(x = long, y = lat,group=group,linetype=id), data = data,colour = pcol,size=psize),
          scale_linetype_discrete(name = position_legend_title),
          theme(legend.position = legend_position)
        )
      ), data = data,pcol=pcol,psize=psize,position_legend_title=position_legend_title,legend_position=legend_position)
    }else{
      outlist <- moveVis::add_gg(r_frame_list, gg = expr(
        list(
          geom_path(aes(x = long, y = lat,group=group), data = data,colour = pcol,size=psize)
        )
      ), data = data,pcol=pcol,psize=psize)
    }
        
  }else if(inherits(positions,"SpatialPointsDataFrame")){
    data <-  data.frame(long=positions@coords[,1],lat=positions@coords[,2],group=as.factor(seq(1,nrow(positions))))
    if(is.null(position_names)){
      position_names <- paste("Point" ,(1:nrow(positions)))
    }else{
      position_names <- as.factor(position_names)
    }
    levels(data$group) <- position_names
    
    if(aes_by_pos){
      outlist <- moveVis::add_gg(r_frame_list, gg = expr(
        list(
          geom_point(aes(x = long, y = lat,group=group,shape=group), data = data,colour = pcol,size=psize),
          scale_shape_discrete(name = position_legend_title),
          theme(legend.position = legend_position)
        )
      ),data = data,pcol=pcol,psize=psize,position_legend_title=position_legend_title,legend_position=legend_position)     
    }else{
      outlist <- moveVis::add_gg(r_frame_list, gg = expr(
        list(
          geom_point(aes(x = long, y = lat,group=group), data = data,colour = pcol,size=psize)
        )
      ),data = data,pcol=pcol,psize=psize)
    }

  }else if(inherits(positions,c("matrix","array"))){
    data <- data.frame(long=positions[,1],lat=positions[,2],group=as.factor(seq(1,nrow(positions))))
    if(is.null(position_names)){
      position_names <- paste("Point" ,(1:nrow(positions)))
    }else{
      position_names <- as.factor(position_names)
    }
    levels(data$group) <- position_names
    if(aes_by_pos){
      outlist  <- moveVis::add_gg(r_frame_list, gg = expr(
        list(
          geom_point(aes(x = long, y = lat,group=group,shape=group), data = data,colour = pcol,size=psize),
          scale_shape_discrete(name = position_legend_title),
          theme(legend.position = legend_position)
        )
      ), data = data,pcol=pcol,psize=psize,position_legend_title=position_legend_title,legend_position=legend_position)
    }else{
      outlist  <- moveVis::add_gg(r_frame_list, gg = expr(
        list(
          geom_point(aes(x = long, y = lat,group=group), data = data,colour = pcol,size=psize),
          scale_shape_discrete(name = position_legend_title),
          theme(legend.position = legend_position)
        )
      ), data = data,pcol=pcol,psize=psize)
    }
    
  }
  
  
  #Optionally add text of position names in a loop
  if(add_text){
    for(i in 1:length(position_names)){
      outlist <- moveVis::add_text(outlist, as.character(position_names[i]), x =coordinates(positions[i,])[1]+t_vjust, y = coordinates(positions[i,])[2]+t_hjust,
                      colour = tcol, size = tsize,type = ttype)
    }
  }
  
return(outlist)

}
