#' Create a series of charts of a raster time series
#'
#' @param r_list list of rasters, as generated by \code{\link{ts_raster}}. 
#' @param positions (Optional) object containing the coordinates. One of \itemize{
##'  \item{A two-column \code{matrix} of coordinates where the first column corresponds to the longitude and the second column corresponds to the latitude.}
##'  \item{A \code{SpatialPolygonsDataFrame} }
##'  \item{A \code{SpatialPointsDataFrame} }
##' }If no positions are specified, one position is assumed to be the entire extent of the rasters.
#' @param position_names (Optional) character, names of the positions to be added in legend or text. By default, will create placeholder names by combining the object type and Id (Example: "Polygon 3")
#' @param val_min (Optional) numeric, minimum value of the y-axis. By default chooses a rounded minimum value of the rasters contained within \code{r_list}.
#' @param val_max (Optional) numeric, maximum value of the y-axis. By default chooses a rounded maximum value of the rasters contained within \code{r_list}.
#' @param val_by (Optional) numeric, interval value of the y-axis. Default is \code{0.1}.
#' @param band_names (Optional) character, names of the positions to be added in legend, if \code{band_legend}. By default, will create placeholder names by band index (Example: "Band 3").
#' @param band_colors (Optional) character, colors which represent the positions in the plot. Must be in matching order to \code{band_names}. By default will use ggplot colors.
#' @param position_legend (Optional) logical. If \code{TRUE}: Add a legend for the positions. Only recommended if \code{aes_by_pos} is also  \code{TRUE}.
#' @param legend_position  (Optional) character, position of the legend. Use \code{"none"} to disable all legends. Default is \code{"right"}.
#' @param band_legend (Optional) logical. If \code{TRUE}: Add a legend for the bands. Default is \code{TRUE}.
#' @param band_legend_title (Optional) character, title of the band legend. Default is \code{"Bands"}.
#' @param position_legend_title (Optional) character, title of the band legend. Default is \code{"Positions"}.
#' @param buffer  (Optional) numeric. The radius of a buffer around each point from which to extract cell values. See \link[raster]{extract} for more details. Default is \code{0}.
#' @param plot_type (Optional) character, type of the plots to produce. Currently supported are \code{"line"} and \code{"violin"}. Default is \code{"line"}. 
#' @param aes_by_pos (Optional) logical. If \code{TRUE}: vary the linetype aesthetic to be different for each position? If  \code{FALSE}, this also disables the \code{position_legend}, as no notable classes will be plotted. Default is \code{TRUE}.
#' @param FUN (Optional) function to summarize the values (e.g. mean) during the extraction. See \link[raster]{extract} for more details. Default is \code{"mean"}. For some \code{plot_type} which map the full distribution of values the FUN is ignored.
#' @param path_size (Optional) numeric, size for the ggplot objects. Default is \code{1}.
#' @details Values are extracted using \link[raster]{extract} and plotted on a \link[ggplot2]{ggplot}.
#'  The type of the ggplot is specified by \code{plot_type}. Currently supported are \code{"line"} and \code{"violin"}.
#'  The function may fail for large polygons and long time series. Be aware that if \code{\link{ts_raster}} is used with \code{fade}, interpolation may be used to generate raster values. 
#' @author Johannes Mast
#' @import sp ggplot2
#' @importFrom grDevices hcl.colors
#' @importFrom dplyr left_join
#' @return A list of ggplots, one for each element of \code{r_list}.
#' @seealso \code{\link{ts_raster}}
#' @export




ts_flow_frames <- function(r_list,positions=NULL,position_names=NULL,band_names=NULL,band_colors=NULL,val_min=NULL,val_max=NULL,val_by=0.1,path_size=1,position_legend=T,legend_position="right",band_legend=T,band_legend_title="Bands",position_legend_title="Positions",buffer=0,plot_type="line",aes_by_pos=T,FUN=mean){
  #Check: If a violin Plot is requested, no aggregation function can be used, as the full sample is required
  if(plot_type=="violin"){
    FUN=NULL
  }
  
  #Ensure nice colors
  if(is.null(band_colors)){
    band_colors <-  hcl.colors(nrow(positions))
  }
  #Ensure nice df names
  if(is.null(band_names)){
    band_names <- paste0("Band",1:(nlayers(r_list_extract[[x]])))  #make artificial bandnames if necessary
  }

  
  ## extract the values of the raster into a long dataframe
  extract_df <- .ts_extract_from_frames(r_list_extract = r_list,
                                                positions = positions,
                                                position_names = position_names,
                                                band_names = band_names,
                                                buffer= buffer,
                                                FUN = FUN)
  
  #For this plot, we need the data in long format
  if(plot_type %in% c("violin","line")){
    extract_df <-  tidyr::pivot_longer(data = extract_df, cols =  band_names) 
  }
  #Make a df to match colors to band names
  color_matching_table <- cbind(band_names,band_colors)
  extract_df <- dplyr::left_join(extract_df,color_matching_table,by = c("name" = "band_names"),copy=T)
  
  
  
  ## create value sequence
  if(is.null(val_min)) val_min <- floor_dec(min(sapply(r_list, minValue), na.rm = T),level = 2)
  if(is.null(val_max)) val_max <- ceiling_dec(max(sapply(r_list, maxValue), na.rm = T),level = 2)
  val_digits <- nchar(strsplit(as.character(val_by), "[.]")[[1]][2])
  if(is.na(val_digits)) val_digits <- 0
  #val_by = NULL
  if(is.null(val_by)){
    #If there are no given vals, just make four
    val_seq <- seq(val_min, val_max, length.out = 4)
  }else{
    #Else make the sequence by the given vals
    val_seq <- seq(val_min, val_max, by = val_by)
  }
  
  
  if(plot_type=="line"){
    flow_frames <- .ts_gg_line(pos_df = extract_df,
                                        position_legend = position_legend,
                                        band_legend = band_legend,
                                        band_legend_title = band_legend_title,
                                        position_legend_title = position_legend_title,
                                        legend_position = legend_position,
                                        path_size =  path_size,
                                        val_seq = val_seq,
                                        aes_by_pos=aes_by_pos)
  }else if(plot_type=="violin"){
    flow_frames <-.ts_gg_vio(pos_df = extract_df,
                                        position_legend = position_legend,
                                        band_legend = band_legend,
                                        band_legend_title = band_legend_title,
                                        position_legend_title = position_legend_title,
                                       legend_position = legend_position,
                                        path_size =  path_size,
                                        val_seq = val_seq,
                                       aes_by_pos=aes_by_pos)
  }

  return(flow_frames)
}
